env:
    node: true
    es2020: true
root: true
ignorePatterns:
    - dist/
extends:
    - eslint:recommended
rules:
    indent:
        - error
        - 4
    quotes:
        - error
        - single
overrides:
    - files:
          - "**/*.ts"
      parser: "@typescript-eslint/parser"
      parserOptions:
          sourceType: module
          ecmaFeatures:
              impliedStrict: true
      plugins:
          - "@typescript-eslint"
      extends:
          - eslint:recommended
          - plugin:@typescript-eslint/eslint-recommended
          - plugin:@typescript-eslint/recommended
