env:
  jest: true
root: true
ignorePatterns:
  - dist/
extends:
  - ./.eslintrc.base.yaml
overrides:
  - files:
      - "**/*.ts"
    plugins:
      - jest
      - "eslint-plugin-tsdoc"
    extends:
      - plugin:jest/recommended
    rules:
      tsdoc/syntax: error
