name: "Security vulnerability scan"

on:
  workflow_call:
    inputs:
      ref:
        description: Branch, tag or SHA to scan.
        type: string
        required: false
        default: ""
      latest-config:
        description: Whether to use the latest OSV Scanner configuration.
        type: boolean
        required: false
        default: false

permissions:
  contents: read

jobs:
  scan:
    name: Scan ${{ matrix.lang }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - lang: go
            config: osv-scanner.toml
          - lang: node
            config: node/osv-scanner.toml
          - lang: java
            config: java/osv-scanner.toml
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          path: src
          ref: ${{ inputs.ref }}
      - name: Checkout latest
        if: ${{ inputs.latest-config || inputs.ref }}
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          path: latest
          sparse-checkout: |
            Makefile
            ${{ matrix.config }}
          sparse-checkout-cone-mode: false
      - name: Set up scan
        if: ${{ inputs.ref }}
        run: |
          cp -f latest/Makefile src/Makefile
      - name: Use latest OSV-Scanner configuration
        if: ${{ inputs.latest-config }}
        run: |
          if [ -r latest/${{ matrix.config }} ]; then
              cp -f latest/${{ matrix.config }} src/${{ matrix.config }}
          fi
      - name: Set up Node
        if: ${{ matrix.lang == 'node' }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "lts/*"
      - name: Scan
        id: scan
        working-directory: src
        run: make scan-${{ matrix.lang }}
        env:
          OSV_SCANNER_ARGS: --format=markdown --output-file=${{ github.workspace }}/osv-scanner.md
      - name: Report failure
        if: ${{ failure() && steps.scan.conclusion == 'failure' }}
        run: |
          cat osv-scanner.md >> ${GITHUB_STEP_SUMMARY}
