name: "Security vulnerability scan"

on:
  workflow_call:
    inputs:
      ref:
        description: Branch, tag or SHA to scan.
        type: string
        required: false
        default: ""
      latest-config:
        description: Whether to use the latest OSV Scanner configuration.
        type: boolean
        required: false
        default: false

permissions:
  contents: read

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          path: src
          ref: ${{ inputs.ref }}
      - name: Checkout latest OSV Scanner configuration
        if: ${{ inputs.latest-config && inputs.ref }}
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          path: latest
          sparse-checkout: |
            osv-scanner.toml
          sparse-checkout-cone-mode: false
      - name: Set up Go
        id: setup-go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: stable
          check-latest: true
          cache: false
      - name: Create OSV-Scanner configuration
        run: |
          if [ -r latest/osv-scanner.toml ]; then
              cp -f latest/osv-scanner.toml src/osv-scanner.toml
          fi
      - name: Scan
        id: scan-go
        working-directory: src
        run: make scan-go
        env:
          OSV_SCANNER_ARGS: --format=markdown --output-file=${{ github.workspace }}/osv-scanner.md
      - name: Report failure
        if: ${{ failure() && steps.scan-go.conclusion == 'failure' }}
        run: |
          cat osv-scanner.md >> ${GITHUB_STEP_SUMMARY}

  node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          path: src
          ref: ${{ inputs.ref }}
      - name: Checkout latest OSV Scanner configuration
        if: ${{ inputs.latest-config && inputs.ref }}
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          path: latest
          sparse-checkout: |
            node/osv-scanner.toml
          sparse-checkout-cone-mode: false
      - name: Use latest OSV-Scanner configuration
        if: ${{ inputs.latest-config && inputs.ref }}
        run: |
          if [ -r latest/node/osv-scanner.toml ]; then
              cp -f latest/node/osv-scanner.toml src/node/osv-scanner.toml
          fi
      - name: Set up Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "lts/*"
      - name: Scan
        id: scan-node
        working-directory: src
        run: make scan-node
        env:
          OSV_SCANNER_ARGS: --format=markdown --output-file=${{ github.workspace }}/osv-scanner.md
      - name: Report failure
        if: ${{ failure() && steps.scan-node.conclusion == 'failure' }}
        run: |
          cat osv-scanner.md >> ${GITHUB_STEP_SUMMARY}

  java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          path: src
          ref: ${{ inputs.ref }}
      - name: Checkout latest OSV Scanner configuration
        if: ${{ inputs.latest-config && inputs.ref }}
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          path: latest
          sparse-checkout: |
            java/osv-scanner.toml
          sparse-checkout-cone-mode: false
      - name: Use latest OSV-Scanner configuration
        if: ${{ inputs.latest-config && inputs.ref }}
        run: |
          if [ -r latest/java/osv-scanner.toml ]; then
              cp -f latest/java/osv-scanner.toml src/java/osv-scanner.toml
          fi
      - name: Scan
        id: scan-java
        working-directory: src
        run: make scan-java
        env:
          OSV_SCANNER_ARGS: --format=markdown --output-file=${{ github.workspace }}/osv-scanner.md
      - name: Report failure
        if: ${{ failure() && steps.scan-java.conclusion == 'failure' }}
        run: |
          cat osv-scanner.md >> ${GITHUB_STEP_SUMMARY}
