name: Scenario test

on:
  workflow_call:

env:
  GO_VERSION: 1.19

jobs:
  go:
    runs-on: ubuntu-22.04
    name: Scenario test Go
    strategy:
      fail-fast: false
      matrix:
        go-version:
          - 1.17
          - 1.18
          - 1.19
    env:
      SOFTHSM2_CONF: ${{ github.workspace }}/softhsm2.conf
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install SoftHSM
        run: ./.github/scripts/install_softhsm.sh
        env:
          TMPDIR: ${{ runner.temp }}
      - name: Pull Fabric Docker images
        run: make pull-latest-peer
      - name: Run scenario tests
        run: make scenario-test-go

  node:
    runs-on: ubuntu-22.04
    name: Scenario test Node
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 14
          - 16
          - 18
    env:
      SOFTHSM2_CONF: ${{ github.workspace }}/softhsm2.conf
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Install SoftHSM
        run: ./.github/scripts/install_softhsm.sh
        env:
          TMPDIR: ${{ runner.temp }}
      - name: Pull Fabric Docker images
        run: make pull-latest-peer
      - name: Run scenario tests
        run: make scenario-test-node

  java:
    runs-on: ubuntu-22.04
    name: Scenario test Java
    strategy:
      fail-fast: false
      matrix:
        java-version:
          - 8
          - 11
          - 17
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: temurin
      - name: Pull Fabric Docker images
        run: make pull-latest-peer
      - name: Run scenario tests
        run: make scenario-test-java
