name: Verify versions

on:
  workflow_call:

permissions:
  contents: read

env:
  GATEWAY_VERSION: 1.8.0

jobs:
  go:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    name: Verify Go version
    steps:
      - name: Check Go module version
        shell: bash
        run: |
          echo "Build ref: ${GITHUB_REF}"
          GO_GATEWAY_VERSION=${GITHUB_REF#refs/tags/v}
          echo "Expected version: ${GATEWAY_VERSION}"
          echo "Go module version (git tag): ${GO_GATEWAY_VERSION}"
          [ "${GO_GATEWAY_VERSION}" = "${GATEWAY_VERSION}" ] || exit 1

  node:
    runs-on: ubuntu-latest
    name: Verify Node version
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Check Node package version
        shell: bash
        working-directory: node
        run: |
          PACKAGE_GATEWAY_VERSION=$(jq --raw-output .version package.json)
          echo "Expected version: ${GATEWAY_VERSION}"
          echo "package.json version: ${PACKAGE_GATEWAY_VERSION}"
          [ "${PACKAGE_GATEWAY_VERSION}" = "${GATEWAY_VERSION}" ] || exit 1

  java:
    runs-on: ubuntu-latest
    name: Verify Java version
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
        with:
          java-version: 21
          distribution: temurin
          cache: maven
      - name: Check Java artifact version
        shell: bash
        working-directory: java
        run: |
          POM_GATEWAY_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Expected version: ${GATEWAY_VERSION}"
          echo "pom.xml version: ${POM_GATEWAY_VERSION}"
          [ "${POM_GATEWAY_VERSION%%-*}" = "${GATEWAY_VERSION}" ] || exit 1
